app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
]

cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('<int:product_productid>/add/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<int:product_productid>/',views.item_clear , name='item_clear'),
    path('item_increment/<int:product_productid>/',views.item_increment , name='item_increment'),
    path('item_decrement/<int:product_productid>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

diseasepredictor/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'diseasepredictor'

urlpatterns = [
    path('RandomForest/', views.covid1, name="covid1"),
    path('a', views.covid2, name="covid2"),
    path('', views.home, name="home"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views

from django.conf.urls.static import static
from django.conf import settings
from polls.views import results

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('',views.initial),

    path('predict/',include('diseasepredictor.urls')),
    path('shop/',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),
    path('my-ajax-test/', views.myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', views.myajaxtestviewtext, name='myajaxtestviewtext'),
    path('payments/', include('payments.urls')),
    path('search/' , views.search_titles ,name = 'search' ),
    path('updates/', include('processdata.urls')),
    path('updates/', include('app.urls')),  # add this
    path('updates/daily/',results,name='home'),


]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from ecommerce.views import search_titles ,myajaxtestview,myajaxtestviewtext


app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('prod_detail/<str:title>',views.prod_detail, name='prod_detail'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<int:product_productid>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),
    path('search/' , search_titles ,name = 'search' ),
    path('my-ajax-test/', myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', myajaxtestviewtext, name='myajaxtestviewtext'),




]

cart/views.py
import stripe 
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from products.models import Product
from users.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages,auth
from django.views.decorators.http import require_POST
from .cart import Cart
from orders.models import Order
from django.core.mail import send_mail
from django.conf import settings
stripe.api_key = settings.STRIPE_SECRET_KEY

@login_required(login_url="/users/login")
def cart_add(request, product_productid):
	cart = Cart(request)
	product = Product.objects.get(productid=product_productid)
	qty = product.quantity
	product.quantity = qty-1
	product.save()
	cart.add(product=product)
	return redirect('/shop/')

# @login_required(login_url="/users/login")
# def cart_detail(request):
# 	sub = []
# 	qty = []
# 	total = 0
# 	for key,value in request.session['cart'].items():
# 		sub.append(float(value['price']) * float(value['quantity']))
# 		qty.append(int(value['quantity']))
# 	for s in sub:
# 		total = total + s
# 	context = {
#     	'title' : 'My Cart',
#     	'sub' : sub,
#     	'total' : total
#     }
# 	return render(request,'cart/cart_detail.html',context)
@login_required(login_url="/users/login")
def cart_detail(request):
	sub = []
	qty = []
	total = 0
	if('cart' in request.session):
		for key,value in request.session['cart'].items():
			sub.append(float(value['price']) * float(value['quantity']))
			qty.append(int(value['quantity']))
		for s in sub:
			total = total + s
		context = {
			'title' : 'My Cart',
			'sub' : sub,
			'total' : total
		}
		return render(request,'cart/cart_detail.html',context)
	else:
		return redirect('/shop')

@login_required(login_url="/users/login")
def item_clear(request,product_productid):
	cart = Cart(request)
	product = Product.objects.get(productid=product_productid)
	qty = product.quantity
	for key,value in request.session['cart'].items():
		if value['productid']==product_productid:
			product.quantity = qty+value['quantity']
			break
	product.save() 
	cart.remove(product)
	return redirect('cart:cart_detail')

@login_required(login_url="/users/login")
def item_increment(request,product_productid):
	cart = Cart(request)
	product = Product.objects.get(productid=product_productid)
	qty = product.quantity
	if qty>0:
		
		for key,value in request.session['cart'].items():
			if value['productid']==product_productid:
				product.quantity = qty-1
				break
		product.save() 
		cart.add(product=product)
		return redirect('cart:cart_detail')
	else:
		messages.info(request,"No more product in the stock!")
		return redirect('cart:cart_detail')


@login_required(login_url="/users/login")
def item_decrement(request,product_productid):
	cart = Cart(request)
	product = Product.objects.get(productid=product_productid)
	qty = product.quantity
	for key,value in request.session['cart'].items():
		if value['productid']==product_productid:
			product.quantity = qty+1
			break
	cart.decrement(product=product)
	product.save() 
	return redirect('cart:cart_detail')

@login_required(login_url="/users/login")
def cart_clear(request):
	cart = Cart(request)
	qty=[]
	pid = []
	for key,value in request.session['cart'].items():
		qty.append(value['quantity'])
		pid.append(value['productid'])
	for i in range(len(pid)):
		product = Product.objects.get(productid=pid[i])
		q = product.quantity
		product.quantity = q+qty[i]
		product.save()
	cart.clear()
	return redirect('cart:cart_detail')

@login_required(login_url="/users/login")
def checkout(request):
	sub = []
	qty = []
	total = 0
	if len(request.session['cart']) != 0:
		for key,value in request.session['cart'].items():
			sub.append(float(value['price']) * float(value['quantity']))
			qty.append(int(value['quantity']))
		for s in sub:
			total = total + s
		context = {
	    	'title' : 'CheckOut',
	    	'sub' : sub,
	    	'total' : total
	    }
		return render(request,'cart/checkout.html',context)
	else:
		messages.info(request,"Your cart Is Empty")
		return redirect('/')

@login_required(login_url="/users/login")
def confrm_checkout(request):
	if len(request.session['cart']) != 0:
		if request.method == 'POST':
			name = request.POST['name']
			phone = request.POST['phonenumber']
			email = request.POST['email']
			address = request.POST['address']
			user_id = request.user.id
			orders=[]
			tot_price=0
			if name and phone and email and address:
				for key,value in request.session['cart'].items():
					item = value['title']
					product_id = value['productid']
					product_object = Product.objects.filter(productid = product_id)[0]
					quantity = value['quantity']
					price = value['price']
					total = (float(quantity) * float(price))
					order = Order(item=item,
					productid=product_object ,
					quantity=quantity,
					price=price,
					total=total,
					name=name,
					phone=phone,
					email=email,
					address=address,
					user_id=user_id
					)
					order.save()
					orders.append(order)
					tot_price += order.total

				content='Hi '+request.user.username+'\n\nYour recent order with order id: '+str(order.id)+' has been successfully placed.\
				Kindly, wait for the Seller to respond to your order.\n'
				send_mail("Order INVOICE", content, settings.SENDER_EMAIL, [request.user.email], fail_silently=False)
				content='Hi '+product_object.user.username+'\n\nCurrently an order with order id: '+str(order.id)+' has been successfully placed at your account.\
				Kindly, check the order and respond favourably to the customer.\n'
				send_mail("Order Alert!!", content, settings.SENDER_EMAIL, [product_object.user.email], fail_silently=False)
				# cart = Cart(request)
				# cart.clear()
				context ={
					'key': settings.STRIPE_PUBLISHABLE_KEY,
        			'orders': orders,
        			'price':int(tot_price)*100,
					'price2':tot_price
				}
				# messages.success(request,'Order Created SuccessFully')
				return render(request, 'payments/home.html', context)
			else:
				messages.info(request,'Filled All The Field')
				return redirect('cart:checkout')
		else:
			messages.warning(request,'SomeThing Went Wrong')
			return redirect('cart:checkout')
	else:
		messages.info(request,"Your cart Is Empty")
		return redirect('/')

templates/cart/cart_detail.html
{% extends "base.html" %}
{% load index %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}


  <div class="col-md-12">

	<table class="table table-inverse mt-3">
		<thead >
			<tr >
				<th style="text-align: center;" >Image</th>
				<th style="text-align: center;">Title</th>
				<th style="text-align: center;">Price</th>
				<th style="text-align: center;">Quantity</th>
				<th style="text-align: center;">SubTotal</th>
				<th style="text-align: center;">Update Order</th>
			</tr>
		</thead>
		<tbody>
{% comment %} {% for j in i %} {% endcomment %}
		    {% for key,value in request.session.cart.items %}



		    <tr>
		        <td><img class="cpi" width="100px" src="{{value.photo}}" alt=""></td>
		        <td>{{value.title}}</td>
		        <td>&#8377;{{value.price}}</td>
		        <td>{{value.quantity}}</td>
				<td>
					&#8377; {{sub|index:forloop.counter0}}
				</td>
				<td>
		            <a class="btn btn-secondary" href="{% url "cart:item_increment" key %}">+</a>&nbsp;
		            <a class="btn btn-secondary" href="{% url "cart:item_decrement" key%}">-</a>&nbsp;
		            <a class="btn btn-danger" href="{% url "cart:item_clear" key %}">Clear</a>&nbsp;
		        </td>



		    </tr>
			{% comment %} {% endfor %} {% endcomment %}

		    {% endfor %}
		    <tr>
		        <td colspan="6" align="right"><b>Total: </b>&#8377; {{total}}</td>
		    </tr>
		    <tr>
		        <td colspan="5" align="right">
		            <a onclick="return confirm('Are You Sure')" class="clearcart btn btn-danger" href="{% url "cart:cart_clear"  %}">Clear cart</a>
		        </td>
		        <td colspan="5" align="right">
		            <a class="btn btn-primary buynow" href="{% url "cart:checkout" %}">Buy now</a>
		        </td>
		</tr>
		</tbody>
	</table>
	 <a class="btn btn-primary buynow" href="{% url "pages:all_products" %}">Continue Shopping</a>
  </div>




{% endblock content %}

templates/cart/checkout.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}


  <div class="col-md-12">
		<div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{{user.profile.image.url}}" alt="" width="72" height="72">
        <h2>Checkout form</h2>
        <p class="lead">Thank You very Much For Purchesing From Us</p>
      </div>

      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{request.session.cart | length}}</span>
          </h4>
          <ul class="list-group mb-3">
			{% for key,value in request.session.cart.items %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{value.title}}</h6>
               </div>
               <span class="text-muted">Quantity {{value.quantity }}</span>
              <span class="text-muted">&#8377;{{value.price}}</span>
            </li>
            {% endfor %}

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (Rupees)</span>
              <strong>&#8377; {{total}} </strong>
            </li>
          </ul>


        </div>

        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Billing address</h4>
          <form class="needs-validation" novalidate method="POST" action="{% url "cart:confrm_checkout" %}">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="" value="{{request.user.username}}" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Phone Number</label>
                <input type="text" class="form-control" name="phonenumber" id="phonenumber" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid Phone Number name is required.
                </div>
              </div>
            </div>



            <div class="mb-3">
              <label for="email">Email <span class="text-muted">(Optional)</span></label>
              <input type="email" name="email" class="form-control" id="email" placeholder="you@example.com" value="{{request.user.email}}">
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="mb-3">
              <label for="address">Address</label>
              <input type="text" class="form-control" name="address" placeholder="1234 Main St" required>
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>




            <hr class="mb-4">

            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info">
              <label class="custom-control-label" for="save-info">Save this information for next time</label>
            </div>
            <hr class="mb-4">

            <!-- <h4 class="mb-3">Payment</h4> -->

            <hr class="mb-4">
            <input class="btn btn-primary btn-sm" value="Proceed For Payment" type="submit">


          </form>
          <a href="{% url "pages:all_products" %}" class="float-right btn btn-primary btn-sm" type="submit">Continue Shopping</a>
        </div>
      </div>
  </div>




{% endblock content %}

templates/cart/confirm.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}


  <div class="col-md-12">

  </div>




{% endblock content %}