app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
]

cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('<int:product_productid>/add/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<int:product_productid>/',views.item_clear , name='item_clear'),
    path('item_increment/<int:product_productid>/',views.item_increment , name='item_increment'),
    path('item_decrement/<int:product_productid>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

diseasepredictor/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'diseasepredictor'

urlpatterns = [
    path('RandomForest/', views.covid1, name="covid1"),
    path('a', views.covid2, name="covid2"),
    path('', views.home, name="home"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views

from django.conf.urls.static import static
from django.conf import settings
from polls.views import results

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('',views.initial),

    path('predict/',include('diseasepredictor.urls')),
    path('shop/',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),
    path('my-ajax-test/', views.myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', views.myajaxtestviewtext, name='myajaxtestviewtext'),
    path('payments/', include('payments.urls')),
    path('search/' , views.search_titles ,name = 'search' ),
    path('updates/', include('processdata.urls')),
    path('updates/', include('app.urls')),  # add this
    path('updates/daily/',results,name='home'),


]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from ecommerce.views import search_titles ,myajaxtestview,myajaxtestviewtext


app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('prod_detail/<str:title>',views.prod_detail, name='prod_detail'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<int:product_productid>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),
    path('search/' , search_titles ,name = 'search' ),
    path('my-ajax-test/', myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', myajaxtestviewtext, name='myajaxtestviewtext'),




]

users/urls.py
from django.urls import path
from . import views
from users.views import SellerSignUpView



app_name = 'users'

urlpatterns = [
    path('login/', views.login_customer, name='login'),
    path('register/', views.register_customer, name='register'),
    path('logout/', views.logout_customer , name='logout'),
    path('dashboard/', views.dashboard_customer , name='dashboard'),
    path('seller/',views.seller_product , name='home'),
    path('seller/order', views.dashboard_seller , name='order'),
    path('seller/order/deliver/<int:order_id>', views.deliver_order , name='order_deliver'),

    path('<int:user_id>/profile/', views.profile_customer , name='profile'),
    path('accounts/signup/teacher/', SellerSignUpView.as_view(), name='teacher_signup'),
    # path('accounts/signup/student/', StudentSignUpView.as_view(), name='student_signup'),
    path('seller/add',views.seller_product_add , name='add'),
    path('seller/product_detail/<int:product_id>',views.seller_product_detail , name='product_detail'),

    # path('myposts/', views.myposts , name='myposts'),
]

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_productid>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:product_productid>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

templates/partials/_footer.html
<br><br><br><br><br>
<footer class="ftco-footer ftco-section">
  <div class="container">
    <div class="row">
      <div class="mouse">
        <a href="#" class="mouse-icon">
          <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
        </a>
      </div>
    </div>
    <div class="row mb-5">
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Groc4All</h2>
          <p>To reach horizons that we can never reach.</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
            <li class="ftco-animate"><a href="#" target="_blank"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#" target="_blank"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#" target="_blank"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-5">
          <!-- <h2 class="ftco-heading-2">Menu</h2> -->

        </div>
      </div>
      <div class="col-md-4">
         <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Help</h2>
          <div class="d-flex">
            <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
              <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
              <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
              <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
              <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
            </ul>
            <ul class="list-unstyled">
              <li><a href="#" class="py-2 d-block">FAQs</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Have Questions?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li><span class="icon icon-map-marker"></span><span class="text">Vellore Institute of Technology, Chennai, Tamil Nadu-600127</span></li>
              <li><a href="#"><span class="icon icon-phone"></span><span class="text">+91 9876543210</span></a></li>
              <li><a href="#"><span class="icon icon-envelope"></span><span class="text">groc4all@gmail.com</span></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | $__TROUBLESHOOTERS__$
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
      </div>
    </div>
  </div>
</footer>

templates/partials/_navbar.html
<style>
.jayit_placeholder::placeholder{
 color: #0b0b14 !important
}

</style>

<div class="py-1 bg-primary">
  <div class="container">
    <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
      <div class="col-lg-12 d-block">
        <div class="row d-flex">
          <div class="col-md pr-4 d-flex topper align-items-center">
            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone-plane"></span></div>
            <span class="text">$__TROUBLESHOOTERS__$</span>
          </div>
          <div class="col-md pr-4 d-flex topper align-items-center">
            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone-plane"></span></div>
            <span class="text">CONTACTUS@gmail.com</span>
          </div>
          <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
            <span class="text">Current day delivery &amp; Free Returns</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
 {%if user.is_authenticated and user.is_customer%}
 <div class="container-fluid">
{%else%}
  <div class="container">
  {%endif%}
    <a class="navbar-brand" href="/">Groc4All</a>

 <div class="nav-item dropdown">
          <input type="text" class="jayit_placeholder" id="search" name="search" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false" placeholder="Search..."/>
          <div class="dropdown-menu" aria-labelledby="search" id="search-results">
          </div>
        </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>





    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
  {%if user.is_authenticated and user.is_customer%}
            <li class="nav-item"><a class="nav-link" href="/shop">SHOP</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">WE CARE FOR YOU</a>
          <div class="dropdown-menu" aria-labelledby="dropdown04">
            <a class="dropdown-item" href="{% url "diseasepredictor:home"%}">CORONA PREDICTOR</a>
            <a class="dropdown-item" href="/updates/">CORONA UPDATES</a>
            <a class="dropdown-item" href="{% url "pages:about" %}">ABOUT US</a>

          </div>
        </li>

{%endif%}
                  {% if user.is_authenticated and user.is_seller%}

                  <li class="nav-item "><a class="nav-link" href="{% url "users:home"%}">YOUR PRODUCTS</a></li>


                  <li class="nav-item "><a class="nav-link" href="{% url "users:order"%}">ORDERS</a></li>


                  <li class="nav-item "><a class="nav-link" href="{% url "users:add"%}">ADD PRODUCTS</a></li>




                   <li class="nav-item ">
                          <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
                          <i class="fas fa-sign-out-alt"></i> Logout
                          </a>

                          <form  method="post" id="logout" action="{% url "users:logout" %}">
                              {% csrf_token %}
                              <input type="hidden">
                          </form>
                  </li>



        {%elif user.is_authenticated and user.is_customer%}
        <li class="nav-item "><a class="nav-link" href="{% url "users:dashboard"%}">DashBoard</a></li>


                  <li class="nav-item "><a class="nav-link" href="{% url "wishlists:my_wishlists"%}">Wishlist</a></li>

                  <li class="nav-item "><a class="nav-link" href="{% url "users:profile" user.id %}">PROFILE</a></li>

                  <li class="nav-item "><a class="nav-link" href="{% url "cart:cart_detail" %}">Cart</a></li>


                   <li class="nav-item ">
                          <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
                          <i class="fas fa-sign-out-alt"></i> Logout
                          </a>

                          <form  method="post" id="logout" action="{% url "users:logout" %}">
                              {% csrf_token %}
                              <input type="hidden">
                          </form>
                  </li>

                  <li class="nav-item "><a href="{% url "cart:cart_detail" %}" class="nav-link">
          <i class="fa fa-cart-plus" style="font-size:14px" aria-hidden="true"></i>
          ({{request.session.cart | length}}) Item
        </a></li>


                  {% else %}
                  {% comment %} <li class="nav-item ">
                    <a class="nav-link" href="{% url "users:register" %}">Register</a>
                  </li> {% endcomment %}

                  <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">REGISTER</a>
          <div class="dropdown-menu" aria-labelledby="dropdown04">
            <a class="dropdown-item" href="{% url "users:register" %}">AS CUSTOMER</a>
            <a class="dropdown-item" href="{% url "users:teacher_signup" %}">AS SELLER</a>

          </div>
        </li>
                  <li class="nav-item ">
                    <a class="nav-link" href="{% url "users:login" %}">Login</a>
                  </li>



                  {% endif %}


      </ul>
    </div>
  </div>
</nav>

templates/partials/_sidebar.html
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>