app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
]

diseasepredictor/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'diseasepredictor'

urlpatterns = [
    path('RandomForest/', views.covid1, name="covid1"),
    path('a', views.covid2, name="covid2"),
    path('', views.home, name="home"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views

from django.conf.urls.static import static
from django.conf import settings
from polls.views import results

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('',views.initial),

    path('predict/',include('diseasepredictor.urls')),
    path('shop/',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),
    path('my-ajax-test/', views.myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', views.myajaxtestviewtext, name='myajaxtestviewtext'),
    path('payments/', include('payments.urls')),
    path('search/' , views.search_titles ,name = 'search' ),
    path('updates/', include('processdata.urls')),
    path('updates/', include('app.urls')),  # add this
    path('updates/daily/',results,name='home'),


]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from ecommerce.views import search_titles ,myajaxtestview,myajaxtestviewtext


app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('prod_detail/<str:title>',views.prod_detail, name='prod_detail'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<int:product_productid>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),
    path('search/' , search_titles ,name = 'search' ),
    path('my-ajax-test/', myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', myajaxtestviewtext, name='myajaxtestviewtext'),




]

users/urls.py
from django.urls import path
from . import views
from users.views import SellerSignUpView



app_name = 'users'

urlpatterns = [
    path('login/', views.login_customer, name='login'),
    path('register/', views.register_customer, name='register'),
    path('logout/', views.logout_customer , name='logout'),
    path('dashboard/', views.dashboard_customer , name='dashboard'),
    path('seller/',views.seller_product , name='home'),
    path('seller/order', views.dashboard_seller , name='order'),
    path('seller/order/deliver/<int:order_id>', views.deliver_order , name='order_deliver'),

    path('<int:user_id>/profile/', views.profile_customer , name='profile'),
    path('accounts/signup/teacher/', SellerSignUpView.as_view(), name='teacher_signup'),
    # path('accounts/signup/student/', StudentSignUpView.as_view(), name='student_signup'),
    path('seller/add',views.seller_product_add , name='add'),
    path('seller/product_detail/<int:product_id>',views.seller_product_detail , name='product_detail'),

    # path('myposts/', views.myposts , name='myposts'),
]

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_productid>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:product_productid>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

templates/seller/add.html
{% extends 'base.html' %}


{% block title %}
    Add Products
{% endblock title %}

{% block content %}
 <div class="col-md-12 container">
        <form action="{% url "users:add"%}" method="POST" enctype="multipart/form-data">


                {% csrf_token %}


        <div class="col-md-6">

           <div class="form-group">
                <label>Title</label>
                {% comment %} value="{{user.username}} {% endcomment %}
                <input type="text" name="title" class="form-control" " >
            </div>

            <div class="form-group">
                <label>price</label>
                <input type="text" name="price" class="form-control" >
            </div>
            <div class="form-group">
                <label>description</label>
                <input type="text" name="description" class="form-control" >
            </div>
            <div class="form-group">
                <label>quantity</label>
                <input type="text" name="quantity" class="form-control" >
            </div>
            {% comment %} <div class="form-group ">
                <label>category</label>
                <input type="text" name="category" class="form-control" >
            </div> {% endcomment %}
            <!-- {% comment %} <div class="form-group" >
                <label>published at</label>
                <input id="date" type="datetime-local"  name="description" class="form-control" >


            </div> {% endcomment %} -->

            <div class="form-group" id="cat1">
                {% if category %}
            <label for="sel1">Select category:</label>
            <select  name="category1" class="form-control" onchange='javascript:{document.getElementById("category").value=document.getElementById("sel1").options[document.getElementById("sel1").selectedIndex].value;}' id="sel1">
                <option disabled selected>--Select Category--</option>
                {%for cat in category%}
                    <option value="{{cat}}">{{cat}}</option>
                {%endfor%}
            </select>
            <input type="hidden" name="category" id="category">
            {% endif %}
            </div>
            <button type="button" class="btn btn-primary" id="addbtn" onclick="addCat()" >Add Category</button>
            <div class="form-group" id="cat2" style="display: None;">
                <label>Add Category</label>
                <input type="text" name="category" class="form-control" >
            </div> 
            <div class="form-group" >
                <label>ADD PRODUCT PICTURE</label>
                <input type="file" name="image" class="form-control">
            </div>

            <div class="form-group" style="width: fit-content;">
                <input type="submit" value="ADD PRODUCT"  class="btn btn-dark btn-block">
            </div>
    </div>
        </form>
    </div>

    <script>
   document.getElementById('date').value = (new Date()).format("m/dd/yy");
   function addCat(){
       document.getElementById('addbtn').style.display='None';
       document.getElementById('cat1').style.display='None';
       document.getElementById('cat2').style.display='Block';
   }
</script>
    {% endblock content %}

templates/seller/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Products</span></p>
            <h1 class="mb-0 bread">Products</h1>
          </div>
        </div>
      </div>
	</div>

	





    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="{% url "users:home" %}" class="active">All</a></li>
    				</ul>
    			</div>
    		</div>
    		<div class="row">
          {% if products %}
    			
				<div class="container">
					<div class="col-md-12 mt-5">
						<h2 class="text-center">My Products</h2>
						<table class="table table-hover table-inverse">
							<thead>
								<tr>
									<th>Product Name</th>
									<th>Quantity</th>
									<th>Price</th>
									<th>Image</th>
									<th>Category</th>
									<th>View</th>
				
								</tr>
							</thead>
							<tbody>
								{%for product in products %}
									<tr>
										<td>{{product.title}}</td>
										<td>{{product.quantity}}</td>
										<td>&#x20B9; {{product.price}}</td>
										<td><img src="{{product.photo.url}}" class="img-thumbnail" height="100px" width="100px" alt=""></td>
										<td>{{product.category}}</td>
										<td><a href="{% url 'users:product_detail' product.productid%}" class="btn btn-primary">Details</a</td>
										
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				
				</div>
          {% else %}
          <p>There is No Product Here!</p>
          {% endif %}
    		</div>
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
	</section>

	{% comment %} <div class="container" style="z-index: 100;">
		<div class="widget">
		   <div class="chat_header">
			  <!--Add the name of the bot here -->
			  <span style="color:white;margin-left: 5px;">Moodbot 😃</span>
			  <span style="color:white;margin-right: 5px;float:right;margin-top: 5px;" id="close">
			  <i class="material-icons">close</i>
			  </span>
		   </div>
		   <!--Chatbot contents goes here -->
		   <div class="chats" id="chats">
			  <div class="clearfix"></div>
		   </div>
		   <!--user typing indicator -->
		   <div class="keypad" >
			  <input type="text" id="keypad" class="usrInput browser-default" placeholder="Type a message..." autocomplete="off">
		   </div>
		</div>
		<!--bot widget -->
		<div class="profile_div" id="profile_div">
		   <img class="imgProfile" src="{% static 'img/botAvatar.png' %}"/>
		</div>
	  </div> {% endcomment %}

		<!-- <section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section> -->
{% endblock %}
{% comment %} {% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

  <div class="col-md-4">
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url "pages:all_products" %}">All Products</a></li>
		{% for cat in categories %}
			<li class="list-group-item"><a href="{% url "pages:category_by_slug" cat.slug %}">{{cat.title}}</a></li>
		{% endfor %}


	</ul>
  </div>




	 <div class="col-md-8">
	 	<div class="row">
			{% for p in products %}
	  <div class="col-md-6 mt-1">
		<div class="card-deck-wrapper">
			<div class="card-deck">
				<div class="card">
					<img class="card-img-top" height="350px" src="{{p.photo.url}}" alt="Card image cap">
					<div class="card-block">
						<h4 class="card-title text-center text-secondary">{{p.title}}</h4>
            <p class="card-text text-center lead">
            {{p.summary}}<br>
            <strong>Category: </strong><a href="{% url "pages:category_by_slug" p.category.slug %}">{{p.category.title}}</a><br>
            <a href="{% url "wishlists:add_wishlist" p.id %}">Add To Wish List</a>
            </p>
						<p class="card-text"><small class="text-info font-weight-bold">Posted At :{{p.published_at}}</small>
						<a href="{% url "pages:product_by_slug" p.slug %}" class="float-right">Read More</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	  </div>
  {% endfor %}
	 	</div>
	 </div>











{% endblock content %}

 {% endcomment %}






{% comment %} {% extends 'base_add.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Products</span></p>
            <h1 class="mb-0 bread">Products</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
              {% for ctg in categories %}
    					<li><a href="{% url "pages:category_by_slug" ctg.slug %}">{{ ctg.title }}</a></li>
              {% endfor %}
    				</ul>
    			</div>
    		</div>
    		<div class="row">
          {% if products %}
          {% for product in products %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url "pages:product_by_slug" product.slug %}" class="img-prod">
						<img class="img-fluid" src="{{ product.photo.url }}" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3>
							<a >{{ product.title }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>${{ product.price }}.00</span></p>
		    					</div>
	    					</div>
    						<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="{% url "pages:product_by_slug" product.slug %}" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
	    							<a href="{% url "wishlists:add_wishlist" product.productid %}"	 class="heart d-flex justify-content-center align-items-center ">
	    								<span><i class="ion-ios-heart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
          {% endfor %}
          {% else %}
          <p>There is No Product Here!</p>
          {% endif %}
    		</div>
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
    </section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
{% endblock %}
{% comment %} {% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

  <div class="col-md-4">
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url "pages:all_products" %}">All Products</a></li>
		{% for cat in categories %}
			<li class="list-group-item"><a href="{% url "pages:category_by_slug" cat.slug %}">{{cat.title}}</a></li>
		{% endfor %}


	</ul>
  </div>




	 <div class="col-md-8">
	 	<div class="row">
			{% for p in products %}
	  <div class="col-md-6 mt-1">
		<div class="card-deck-wrapper">
			<div class="card-deck">
				<div class="card">
					<img class="card-img-top" height="350px" src="{{p.photo.url}}" alt="Card image cap">
					<div class="card-block">
						<h4 class="card-title text-center text-secondary">{{p.title}}</h4>
            <p class="card-text text-center lead">
            {{p.summary}}<br>
            <strong>Category: </strong><a href="{% url "pages:category_by_slug" p.category.slug %}">{{p.category.title}}</a><br>
            <a href="{% url "wishlists:add_wishlist" p.id %}">Add To Wish List</a>
            </p>
						<p class="card-text"><small class="text-info font-weight-bold">Posted At :{{p.published_at}}</small>
						<a href="{% url "pages:product_by_slug" p.slug %}" class="float-right">Read More</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	  </div>
  {% endfor %}
	 	</div>
	 </div>




	 <div class="container" style="z-index: 100;">
		<div class="widget">
		   <div class="chat_header">
			  <!--Add the name of the bot here -->
			  <span style="color:white;margin-left: 5px;">Moodbot 😃</span>
			  <span style="color:white;margin-right: 5px;float:right;margin-top: 5px;" id="close">
			  <i class="material-icons">close</i>
			  </span>
		   </div>
		   <!--Chatbot contents goes here -->
		   <div class="chats" id="chats">
			  <div class="clearfix"></div>
		   </div>
		   <!--user typing indicator -->
		   <div class="keypad" >
			  <input type="text" id="keypad" class="usrInput browser-default" placeholder="Type a message..." autocomplete="off">
		   </div>
		</div>
		<!--bot widget -->
		<div class="profile_div" id="profile_div">
		   <img class="imgProfile" src="{% static 'img/botAvatar.png' %}"/>
		</div>
	  </div>






{% endblock content %}

 {% endcomment %}

templates/seller/product_detail.html
{% extends "base.html" %}


{% block title %}
    Update Products
{% endblock title %}

{% block content %}
 <div class="col-md-6 container">
        <form action="{% url "users:product_detail" product.productid%}" method="POST" enctype="multipart/form-data">

                {% csrf_token %}


        <div class="col-md-6 float-left" >

           <div class="form-group">
                <label>Product Name</label>
                <input type="text" name="title" value="{{ product.title }}" class="form-control-plaintext" readonly >
            </div>

            <div class="form-group">
                <label>Price</label>
                <input type="number" name="price" value="{{product.price}}" class="form-control" >
            </div>
            <div class="form-group">
                <label>Description</label>
                <input type="text" name="description" value="{{product.description}}" class="form-control" >
            </div>
            <div class="form-group">
                <label>Quantity</label>
                <input type="number" name="quantity" value="{{ product.quantity }}" class="form-control" >
            </div>
            <div class="form-group">
                <label>Category</label>
                <input type="text" name="category" class="form-control-plaintext" value="{{ product.category }}"  readonly >
            </div>
            <!-- <div class="form-group" >
                <label>Published at</label>
                <input id="date" type="datetime-local"  name="description" value="{{ product.published_at }}"  class="form-control" readonly>
            </div> -->
            <!-- <div class="form-group" >
                <label>ADD PRODUCT PICTURE</label>
                <input type="file" name="image" class="fomr-control">
            </div> -->

        </div>

        <div class="col-md-6 float-right">
             <div>
                <img src="{{product.photo.url}}" class="img-thumbnail" alt="">
            </div> 
            
        </div>

        <div class="form-group" style="width: fit-content;">
            <input type="submit" value="UPDATE PRODUCT"  class="btn btn-dark btn-block">
        </div>

        </form>
    </div>

    <script>
   document.getElementById('date').value = (new Date()).format("m/dd/yy");
</script>
    {% endblock content %}

templates/seller/sellerorder.html
{% extends "base.html" %}

{% comment %} {%for orders in order_seller%} {% endcomment %}
{% comment %} {{x}} {% endcomment %}

{% block title %}
    {{title|upper}}
{% endblock title %}



{% block content %}

  <div class="col-md-12 mt-5">
  	<h1 class="text-center">My Orders</h1>
	 <table class="table table-hover table-inverse">
	 	<thead>
	 		<tr>
                <th>Order ID</th>
	 			<th>Item Name</th>
                <th>Price</th>
	 			<th>Quantity</th>
	 			<th>Total</th>
                <th>Customer Name</th>
	 			<th>Customer Phone</th>
                <th>Customer Address</th>
	 			<th>Customer Email</th>
                <th>Order Status</th>

	 		</tr>
	 	</thead>
	 	<tbody>
	 		{% for ord in Order %}
                {%for orders in ord%}
				<tr>
					<td>{{orders.id}}</td>
					<td>{{orders.item}}</td>
					<td>{{orders.price}}</td>
					<td>{{orders.quantity}}</td>
                    <td>{{orders.total}}</td>
                    <td>{{orders.name}}</td>
                    <td>{{orders.phone}}</td>
					<td>{{orders.address}}</td>
					<td>{{orders.email}}</td>
					{% if orders.delivery  %}
						<td>Delivered</td>
					{% else %}
					   <td>Delivery Pending<br>
					    <a type="button" class="btn btn-info" href="{% url 'users:order_deliver' orders.id %}">Done</a></td>
					{% endif %}
				</tr>
                {%endfor%}
            {%endfor%}
	 	</tbody>
	 </table>
  </div>




{% endblock content %}





{% comment %} {% for ord in order %}
    {%for orders in ord%}
        {% comment %} {%for i in orders%}
    {{i.id}}
    {%endfor%} {% endcomment %}
    {% comment %} ID :{{orders.id}}
    <br>
    ITEM: {{orders.item}}

    <br> {% endcomment %}

{% comment %} {%endfor%}
{%endfor%} {% endcomment %}

{% comment %} {%endfor%} {% endcomment %}

templates/seller/signup_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}