app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
]

cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('<int:product_productid>/add/',views.cart_add , name='cart_add'),
    path('cart_detail',views.cart_detail , name='cart_detail'),
    path('item_clear/<int:product_productid>/',views.item_clear , name='item_clear'),
    path('item_increment/<int:product_productid>/',views.item_increment , name='item_increment'),
    path('item_decrement/<int:product_productid>/',views.item_decrement , name='item_decrement'),
    path('checkout/',views.checkout,name='checkout'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
	path('confrm_checkout/',views.confrm_checkout , name='confrm_checkout'),
]

diseasepredictor/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'diseasepredictor'

urlpatterns = [
    path('RandomForest/', views.covid1, name="covid1"),
    path('a', views.covid2, name="covid2"),
    path('', views.home, name="home"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views

from django.conf.urls.static import static
from django.conf import settings
from polls.views import results

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('',views.initial),

    path('predict/',include('diseasepredictor.urls')),
    path('shop/',include('pages.urls')),
    path('cart/',include('cart.urls')),
    path('users/',include('users.urls')),
    path('wishlists/',include('wishlists.urls')),
    path('my-ajax-test/', views.myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', views.myajaxtestviewtext, name='myajaxtestviewtext'),
    path('payments/', include('payments.urls')),
    path('search/' , views.search_titles ,name = 'search' ),
    path('updates/', include('processdata.urls')),
    path('updates/', include('app.urls')),  # add this
    path('updates/daily/',results,name='home'),


]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
from ecommerce.views import search_titles ,myajaxtestview,myajaxtestviewtext


app_name = 'pages'

urlpatterns = [
    path('', views.home , name='home'),
    path('prod_detail/<str:title>',views.prod_detail, name='prod_detail'),
    path('about/', views.about , name='about'),
    path('all_products/', views.all_products , name='all_products'),
    path('<int:product_productid>/',views.product_by_slug , name='product_by_slug'),
    path('category/<slug:slug>/',views.category_by_slug , name='category_by_slug'),
    path('search/' , search_titles ,name = 'search' ),
    path('my-ajax-test/', myajaxtestview, name='myajaxtestview'),
    path('my-ajax-test-text/', myajaxtestviewtext, name='myajaxtestviewtext'),




]

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_productid>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:product_productid>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

templates/ecom/all_products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Products</span></p>
            <h1 class="mb-0 bread">Products</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
              <!-- {% for ctg in categories %}
    					<li><a href="{% url "pages:category_by_slug" ctg.slug %}">{{ ctg.title }}</a></li>
              {% endfor %} -->
    				</ul>
    			</div>
    		</div>
    		<div class="row">
          {% if products %}
          {% for product in products %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url "pages:product_by_slug" product.productid %}" class="img-prod">
						<img class="img-fluid" src="{{ product.photo.url }}" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3>
							<a >{{ product.title }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>&#8377;{{ product.price }}.00</span></p>
		    					</div>
	    					</div>
    						<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="{% url "pages:product_by_slug" product.productid %}" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
	    							<a href="{% url "wishlists:add_wishlist" product.productid %}"	 class="heart d-flex justify-content-center align-items-center ">
	    								<span><i class="ion-ios-heart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
          {% endfor %}
          {% else %}
          <p>There is No Product Here!</p>
          {% endif %}
    		</div>
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
    </section>

		<!-- <section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section> -->
{% endblock %}
{% comment %} {% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

  <div class="col-md-4">
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url "pages:all_products" %}">All Products</a></li>
		{% for cat in categories %}
			<li class="list-group-item"><a href="{% url "pages:category_by_slug" cat.slug %}">{{cat.title}}</a></li>
		{% endfor %}


	</ul>
  </div>




	 <div class="col-md-8">
	 	<div class="row">
			{% for p in products %}
	  <div class="col-md-6 mt-1">
		<div class="card-deck-wrapper">
			<div class="card-deck">
				<div class="card">
					<img class="card-img-top" height="350px" src="{{p.photo.url}}" alt="Card image cap">
					<div class="card-block">
						<h4 class="card-title text-center text-secondary">{{p.title}}</h4>
            <p class="card-text text-center lead">
            {{p.summary}}<br>
            <strong>Category: </strong><a href="{% url "pages:category_by_slug" p.category.slug %}">{{p.category.title}}</a><br>
            <a href="{% url "wishlists:add_wishlist" p.id %}">Add To Wish List</a>
            </p>
						<p class="card-text"><small class="text-info font-weight-bold">Posted At :{{p.published_at}}</small>
						<a href="{% url "pages:product_by_slug" p.slug %}" class="float-right">Read More</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	  </div>
  {% endfor %}
	 	</div>
	 </div>




	 <div class="container" style="z-index: 100;">
		<div class="widget">
		   <div class="chat_header">
			  <!--Add the name of the bot here -->
			  <span style="color:white;margin-left: 5px;">Moodbot 😃</span>
			  <span style="color:white;margin-right: 5px;float:right;margin-top: 5px;" id="close">
			  <i class="material-icons">close</i>
			  </span>
		   </div>
		   <!--Chatbot contents goes here -->
		   <div class="chats" id="chats">
			  <div class="clearfix"></div>
		   </div>
		   <!--user typing indicator -->
		   <div class="keypad" >
			  <input type="text" id="keypad" class="usrInput browser-default" placeholder="Type a message..." autocomplete="off">
		   </div>
		</div>
		<!--bot widget -->
		<div class="profile_div" id="profile_div">
		   <img class="imgProfile" src="{% static 'img/botAvatar.png' %}"/>
		</div>
	  </div>






{% endblock content %}

 {% endcomment %}

templates/ecom/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Products</span></p>
            <h1 class="mb-0 bread">Products</h1>
          </div>
        </div>
      </div>
	</div>





    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
              {% for ctg in category %}
    					<li><a href="{% url "pages:category_by_slug" ctg.slug %}">{{ ctg.title }}</a></li>
              {% endfor %}
    				</ul>
    			</div>
    		</div>
    		<div class="row">
          {% if products %}
          {% for product in products %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url "pages:prod_detail" product.title %}" class="img-prod">
						<img class="img-fluid" src="{{ product.photo.url }}" alt="Colorlib Template">
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3>
							<a >{{ product.title }}</a></h3>
    						<!-- <div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span>&#x20B9; {{ product.price }}.00</span></p>
		    					</div>
	    					</div> -->
    						<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="{% url "pages:prod_detail" product.title%}" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<!-- <a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
									</a> -->
	    							<a href="{% url "wishlists:add_wishlist" product.productid %}"	 class="heart d-flex justify-content-center align-items-center ">
	    								<span><i class="ion-ios-heart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
          {% endfor %}
          {% else %}
          <p>There is No Product Here!</p>
          {% endif %}
    		</div>
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
	</section>

	{% comment %} <div class="container" style="z-index: 100;">
		<div class="widget">
		   <div class="chat_header">
			  <!--Add the name of the bot here -->
			  <span style="color:white;margin-left: 5px;">Moodbot 😃</span>
			  <span style="color:white;margin-right: 5px;float:right;margin-top: 5px;" id="close">
			  <i class="material-icons">close</i>
			  </span>
		   </div>
		   <!--Chatbot contents goes here -->
		   <div class="chats" id="chats">
			  <div class="clearfix"></div>
		   </div>
		   <!--user typing indicator -->
		   <div class="keypad" >
			  <input type="text" id="keypad" class="usrInput browser-default" placeholder="Type a message..." autocomplete="off">
		   </div>
		</div>
		<!--bot widget -->
		<div class="profile_div" id="profile_div">
		   <img class="imgProfile" src="{% static 'img/botAvatar.png' %}"/>
		</div>
	  </div> {% endcomment %}

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

<div class="container">
  <div class="widget">
     <div class="chat_header">
        <!--Add the name of the bot here -->
        <span style="color:white;margin-left: 5px;">Moodbot 😃</span>
        <span style="color:white;margin-right: 5px;float:right;margin-top: 5px;" id="close">
        <i class="material-icons">close</i>
        </span>
     </div>
     <!--Chatbot contents goes here -->
     <div class="chats" id="chats">
        <div class="clearfix"></div>
     </div>
     <!--user typing indicator -->
     <div class="" style="display:flex;">
        <input type="text" id="keypad" style="display:flex" class="usrInput browser-default" placeholder="Type a message..." autocomplete="off" autofocus>
         {% comment %} <form action='#' class="nobgform" style="display:flex" > {% endcomment %}
          {% comment %} {%csrf_token%} {% endcomment %}
          <input type="submit" class="nobg browser-default"  name="mybtn" autocomplete="off">
        {% comment %} </form> {% endcomment %}
     </div>
  </div>
  <!--bot widget -->
  <div class="profile_div" id="profile_div">
     <img class="imgProfile" src="/static/img/botAvatar.png"/>
  </div>
</div>

{% endblock %}

templates/ecom/prod_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="#">Home</a></span> <span>Products</span></p>
            <h1 class="mb-0 bread">Products</h1>
          </div>
        </div>
      </div>
	</div>





    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
                            {% for ctg in category %}
    					<li><a href="{% url "pages:category_by_slug" ctg.slug %}">{{ ctg.title }}</a></li>
                            {% endfor %}
    				</ul>
    			</div>
            </div>
            <div class="col-md-4 ">
                <img class="img-fluid" src="{{image}}" alt="Colorlib Template">
            </div>
            <div class="col-md-4">
                <h3>{{title}}</h3>
            </div><br>
    		<div class="row">
          {% if products %}
    			
                <div>
					<div class="col-md-12  mt-5">
						<table class="table table-hover table-inverse">
							<thead>
								<tr>
									<th>S.No</th>
									<th>Seller Name</th>
									<th>Price</th>
									<th>Quantity</th>
									<th>Category</th>
									<th>Detail</th>
				
								</tr>
							</thead>
							<tbody>
								{%for product in products %}
									<tr>
										<td>{{forloop.counter}}</td>
										<td>{{product.user.username}}</td>
										<td>&#x20B9; {{product.price}}</td>
                                        <!-- <td><img src="{{product.photo.url}}" class="img-thumbnail" height="100px" width="100px" alt=""></td> -->
                                        {% if product.quantity == 0 %}
                                        <td>Out of Stock</td>
                                        <td>{{product.category}}</td>
                                        <td><a href="{% url 'pages:product_by_slug' product.productid%}" class="btn btn-primary" disabled>View</a</td>
                                        {%else%}
                                        <td>{{product.quantity}}</td>                                   
                                        <td>{{product.category}}</td>
										<td><a href="{% url 'pages:product_by_slug' product.productid%}" class="btn btn-primary">View</a</td>
                                            {% endif %}
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				
				</div>
          {% endif %}
    		</div>
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
    </section>
    {% endblock %}

templates/ecom/search.html
{% if articles.count > 0%}



{%for article in articles%}
<a class="dropdown-item" href="/shop/{{article.productid}}/">{{article.title}}</a>






{% endfor %}
{%else%}
<li>!  Nothing Found  !</li>
{%endif%}

templates/ecom/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2">
            {% comment %} <a href="{% url 'home' %}">Home</a></span> <span class="mr-2"> {% endcomment %}
            <a href="index.html">Product</a></span> <span>Product Single</span></p>
            <h1 class="mb-0 bread">Product Single</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row">
    			<div class="col-lg-6 mb-5 ftco-animate">
    				<a href="{{ product.photo.url }}" class="image-popup"><img src="{{ product.photo.url }}" class="img-fluid" alt="Colorlib Template"></a>
    			</div>
    			<div class="col-lg-6 product-details pl-md-5 ftco-animate">
    				<h3>{{ product.name }}</h3>
    				<div class="rating d-flex">
							<p class="text-left mr-4">
								<a href="#" class="mr-2">5.0</a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
								<a href="#"><span class="ion-ios-star-outline"></span></a>
							</p>
							<p class="text-left mr-4">
								<a href="#" class="mr-2" style="color: #000;">100 <span style="color: #bbb;">Rating</span></a>
							</p>
							<p class="text-left">
								<a href="#" class="mr-2" style="color: #000;">500 <span style="color: #bbb;">Sold</span></a>
							</p>
						</div>
    				<p class="price"><span>&#x20B9; {{ product.price }}</span></p>
    				<p>{{ product.details }}</p>
                                <p>{{product.description}}</p>

						<div class="row mt-4">
							<div class="col-md-6">
								<div class="form-group d-flex">
		              <div class="select-wrap">
	                  <div class="icon">
                    {% comment %} <span class="ion-ios-arrow-down"></span> {% endcomment %}
                    </div>
	                  {% comment %} <select name="" id="" class="form-control">
	                  	<option value="">Small</option>
	                    <option value="">Medium</option>
	                    <option value="">Large</option>
	                    <option value="">Extra Large</option>
	                  </select> {% endcomment %}
	                </div>
		            </div>
							</div>
							<div class="w-100"></div>
							<div class="input-group col-md-6 d-flex mb-3">
	             	{% comment %} <span class="input-group-btn mr-2">
	                	<button type="button" class="quantity-left-minus btn"  data-type="minus" data-field="">
	                   <i class="ion-ios-remove"></i>
	                	</button>
	            		</span>
	             	<input type="text" id="quantity" name="quantity" class="form-control input-number" value="1" min="1" max="100">
	             	<span class="input-group-btn ml-2">
	                	<button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
	                     <i class="ion-ios-add"></i>
	                 </button>
	             	</span> {% endcomment %}
	          	</div>
	          	<div class="w-100"></div>
	          	<div class="col-md-12">
	          		<p style="color: #000;">{{product.quantity}} LEFT IN STOCK</p>
	          	</div>
          	</div>
          	<p><a href="{% url "cart:cart_add" product.productid %}" class="btn btn-black py-10 px-5">Add to Cart</a></p>
    			</div>
    		</div>
    	</div>
	</section>


	<div class="container" style="z-index: 100;">
		<div class="widget">
		   <div class="chat_header">
			  <!--Add the name of the bot here -->
			  <span style="color:white;margin-left: 5px;">Moodbot 😃</span>
			  <span style="color:white;margin-right: 5px;float:right;margin-top: 5px;" id="close">
			  <i class="material-icons">close</i>
			  </span>
		   </div>
		   <!--Chatbot contents goes here -->
		   <div class="chats" id="chats">
			  <div class="clearfix"></div>
		   </div>
		   <!--user typing indicator -->
		   <div class="keypad" >
			  <input type="text" id="keypad" class="usrInput browser-default" placeholder="Type a message..." autocomplete="off">
		   </div>
		</div>
		<!--bot widget -->
		<div class="profile_div" id="profile_div">
		   <img class="imgProfile" src="{% static 'img/botAvatar.png' %}"/>
		</div>
	  </div>

    <section class="ftco-section">
    	<div class="container">
				<div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
          	<span class="subheading">Products</span>
            <h2 class="mb-4">Related Products</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
          </div>
        </div>
    	</div>
    	<div class="container">
    		<div class="row">
          {% for rel_product in related_products %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="#" class="img-prod"><img class="img-fluid" src="{{ rel_product.photo.url }}" alt="Colorlib Template">
    						<span class="status">30%</span>
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">{{ rel_product.title }}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
		    						<p class="price"><span class="mr-2 price-dc">&#8377;{{ rel_product.price }}</span><span class="price-sale">${{ rel_product.price }}</span></p>
		    					</div>
	    					</div>
	    					<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="#" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
	    							<a href="#" class="heart d-flex justify-content-center align-items-center ">
	    								<span><i class="ion-ios-heart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
          {% endfor %}
    		</div>
    	</div>
    </section>

		<!-- <section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section> -->
    <script>
      $(document).ready(function(){

      var quantitiy=0;
         $('.quantity-right-plus').click(function(e){

              // Stop acting like a button
              e.preventDefault();
              // Get the field name
              var quantity = parseInt($('#quantity').val());

              // If is not undefined

                  $('#quantity').val(quantity + 1);


                  // Increment

          });

           $('.quantity-left-minus').click(function(e){
              // Stop acting like a button
              e.preventDefault();
              // Get the field name
              var quantity = parseInt($('#quantity').val());

              // If is not undefined

                  // Increment
                  if(quantity>0){
                  $('#quantity').val(quantity - 1);
                  }
          });

      });
    </script>
{% endblock %}



{% comment %} {% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

  <div class="col-md-4 mt-4">
	<ul class="list-group">
		<li class="list-group-item"><a href="{% url "pages:all_products" %}">All Products</a></li>

	</ul>
  </div>
  <div class="col-md-8 mt-4">
	<h1 class="page-header">{{product.title}}</h1>
	<img  src="{{product.photo.url}}" width="400px" class="img-thumbnail" alt="">
    <br>
    <p>{{product.description}}</p>
    <p>Price : ${{product.price}}</p>
    <p>Avaiable : {{product.quantity}}</p>
    <p><a href="{% url "cart:cart_add" product.slug %}">Add to cart</a></p>

  </div>




{% endblock content %}

 {% endcomment %}